### ISSUE TITLE
WHERE ARE THE SET UP INSTRUCTIONS????????

### ISSUE THREAD

**Issue by acc-nicholas** [clapinton/super-mario-ticzz-tuckzz#1]
DO YOU REALLY EXPECT ME TO FIGURE THIS OUT ON MY OWN? ITS LIKE YOU DONT WANT TO SHARE THIS WITH THE WORLD.

**Comment by olivetreee** [comment]
RTFM, Nick
:point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down:
:point_right:   https://github.com/liquidx/webviewscreensaver    :point_left:
:point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up:
